name: CMake Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
          sudo apt-get install -y cmake libxrandr-dev libx11-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev mesa-common-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake curl  # Only install curl on macOS

      - name: Configure CMake (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          cmake -S . -B build -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -DCMAKE_CXX_STANDARD=20 -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release